CONDA_BUILD_SYSROOT:       # [osx and x86]
  - /opt/MacOSX10.14.sdk   # [osx and x86]
macos_min_version:         # [osx and x86]
  - 10.14                  # [osx and x86]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86]
  - 10.14                  # [osx and x86]
c_compiler:                # [win]
  - vs2019                 # [win]
cxx_compiler:              # [win]
  - vs2019                 # [win]
vc:
  - 14                     # [win]