{% set name = "tensorstore" %}
{% set version = "0.1.72" %}
# Bazel version is specified upstream, file .bazelversion
# https://github.com/google/tensorstore/blob/master/.bazelversion
{% set bazel_version = "7.*" %}
# tensorstore >=0.1.77 need bazel 8.* (channel latest available 7.6.1)

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tensorstore-{{ version }}.tar.gz
  sha256: 763d7f6898711783f199c8226a9c0b259546f5c6d9b4dc0ad3c9e39627060022
  patches:
    # MacOS needs an extra linker flag so pybind11 finds the python symbols in _tensorstore.so :shrug:
    - patches/0001-pybind11-linkopts.patch  # [osx]
    - patches/0002-jpeg-require-image-boolean.patch
    - patches/0003-system-libs-fix-include-unvendoring.patch

build:
  skip: true  # [py<310 or win]
  number: 0
  ignore_run_exports:
    - libprotobuf
    - pybind11-abi
    - libcxx
    - numpy
  # conda-build check binaries on linux-aarch64 failed due to ELF_DYNAMIC_TAGS is not supported TAG,
  # which is not supported by lief (tested with lief 0.16.4 and 0.16.6).
  # This is a workaround to ignore the overlinking error.
  # Issue reproduced on conda-build 26.1.0 (latest)
  # Fix in development is here: https://github.com/conda/conda-build/pull/5778
  overlinking_ignore_patterns:  # [linux and aarch64]
    - "**/site-packages/tensorstore/_tensorstore.cpython-*-aarch64-linux-gnu.so"  # [linux and aarch64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - bazel {{ bazel_version }}
    - bazel-toolchain
    # https://github.com/conda-forge/bazel-toolchain-feedstock/pull/22
    - bazel-toolchain <0.3                # [osx]
  host:
    - pip
    - python
    - wheel
    - setuptools >=64
    - setuptools-scm >=8.1.0
    - numpy {{ numpy }}
    # we use openssl instead of boringssl
    - openssl {{ openssl }}
    - bzip2 {{ bzip2 }}
    - blosc {{ blosc }}
    - libcurl {{ libcurl }}
    - jpeg {{ jpeg }}
    - libtiff {{ libtiff }}
    - libpng {{ libpng }}
    - libwebp {{ libwebp }}
    - zlib {{ zlib }}
    - libavif {{ libavif }}
    # py::dtype::num() add support in pybind11 >=2.10.0
    - pybind11 >=2.10.0,<3
    - pybind11-abi
    - lz4
    - nlohmann_json
  run:
    - ml_dtypes >=0.3.1
    - python >=3.10
    - numpy >=1.22.0

test:
  source_files:
    - python/tensorstore/tests
  imports:
    - tensorstore
  requires:
    - pip
    - pytest
    - ml_dtypes
    - cloudpickle
    - numpy {{ numpy }}
    - anyio
    - pytest-asyncio
    - pytest-tornasync
    - pytest-trio
  commands:
    - pip check
    - pytest -ra -v --tb=short python/tensorstore/tests -k "not slow and not (test_add or test_open_array_driver or test_array_no_copy or test_array_no_write)"

about:
  home: https://pypi.org/project/tensorstore
  license: Apache-2.0 AND MIT AND BSD-3-Clause AND BSD-2-Clause
  license_file:
    - LICENSE
    - licenses/com_google_absl.txt
    - licenses/com_google_re2.txt
    - licenses/com_google_riegeli.txt
    - licenses/net_sourceforge_half.txt
  summary: Read and write large, multi-dimensional arrays
  description: |
    TensorStore is an open-source C++ and Python software library designed for 
    storage and manipulation of large multi-dimensional arrays
  dev_url: https://github.com/google/tensorstore
  doc_url: https://google.github.io/tensorstore

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - traversaro
