{% set name = "tensorstore" %}
{% set version = "0.1.65" %}
# Bazel version is specified upstream, file .bazelversion
# https://github.com/google/tensorstore/blob/master/.bazelversion
{% set bazel_version = "6.*" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tensorstore-{{ version }}.tar.gz
  sha256: 65cbe5a600c32569bb0b9f597ea318cc298a13b42d5fc98168c97bb11f320eae
  patches:
    # MacOS needs an extra linker flag so pybind11 finds the python symbols in _tensorstore.so :shrug:
    - patches/pybind11-linkopts.patch  # [osx]
    - patches/0001-Explicitly-select-blake3-for-arm64.patch  # [osx or linux-aarch64]
    - patches/0002-jpeg-require-image-boolean.patch

build:
  skip: true  # [py<39 or win or linux]
  number: 6
  ignore_run_exports:
    - libprotobuf
    - pybind11-abi
    - libcxx
    - numpy

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - bazel {{ bazel_version }}
    - bazel-toolchain
    # https://github.com/conda-forge/bazel-toolchain-feedstock/pull/22
    - bazel-toolchain <0.3                # [osx]
    # - pybind11
    # - pybind11-abi
  host:
    - pip
    - python
    - wheel
    - setuptools >=30.3.0
    - setuptools-scm >=8.1.0
    - numpy {{ numpy }}
    # we use openssl instead of boringssl
    - openssl {{ openssl }}
    - bzip2 {{ bzip2 }}
    - blosc {{ blosc }}
    - libcurl {{ libcurl }}
    - jpeg {{ jpeg }}
    - libpng {{ libpng }}
    - libwebp {{ libwebp }}
    - zlib {{ zlib }}
    - libprotobuf {{ libprotobuf }}
    - libavif {{ libavif }}
    - pybind11
    - pybind11-abi
    - lz4
    # Use the one from https://github.com/google/tensorstore/blob/master/third_party/com_github_nlohmann_json/workspace.bzl
    - nlohmann_json
  run:
    - ml_dtypes >=0.3.1
    - python >=3.9

test:
  source_files:
    - python/tensorstore/tests
  imports:
    - tensorstore
  requires:
    - pip
    - pytest
    - ml_dtypes
    - cloudpickle
    - numpy {{ numpy }}
  commands:
    - pip check
    - pytest -ra -v --tb=short python/tensorstore/tests

about:
  home: https://pypi.org/project/tensorstore
  license: Apache-2.0 AND MIT AND BSD-3-Clause AND BSD-2-Clause
  license_file:
    - LICENSE
    - licenses/com_google_absl.txt
    - licenses/com_google_re2.txt
    - licenses/com_google_riegeli.txt
    - licenses/net_sourceforge_half.txt
  summary: Read and write large, multi-dimensional arrays
  description: |
    TensorStore is an open-source C++ and Python software library designed for 
    storage and manipulation of large multi-dimensional arrays
  dev_url: https://github.com/google/tensorstore
  doc_url: https://google.github.io/tensorstore/

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - traversaro
